#!/usr/bin/env python3

import os
from typing import Any, Mapping
from datetime import date
from collections import defaultdict


import click
from my.mal.export import anime, manga


@click.command()
@click.argument("ORDER", type=click.Choice(["most", "date"]), default="date")
def main(order: str) -> None:
    """ """

    username = os.environ["MAL_USERNAME"]
    day_watching: Mapping[date, Any] = defaultdict(list)

    # anime
    for a in filter(lambda an: an.username == username, anime()):
        for item in a.history:
            day_watching[item.at.date()].append(
                (item, a.XMLData.title, "Watched episode")
            )

    # manga
    for m in filter(lambda mn: mn.username == username, manga()):
        for item in m.history:
            day_watching[item.at.date()].append((item, m.XMLData.title, "Read chapter"))

    # sort
    if order == "date":
        day_order = sorted(set(day_watching.keys()))
    else:
        day_order = (
            day
            for day, _ in sorted(
                [(day, len(entries)) for day, entries in day_watching.items()],
                key=lambda t: t[1],
                reverse=True,
            )
        )

    # print
    for day in day_order:
        print(str(day))
        for item in day_watching[day]:
            print("\t", end="")
            print(f"{item[0].at} {item[2]} {item[0].number} of {item[1]}")


if __name__ == "__main__":
    main()
